server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # C'est la ligne magique qui redirige tout vers React Router :
        try_files $uri $uri/ /index.html;
    }
}