sonar.projectKey=traaaash_PFA
sonar.organization=traaaash
sonar.projectName=PFA Ticketing App
sonar.projectVersion=1.0

# Source directories
sonar.sources=backend,frontend/src

# Python (Backend)
sonar.python.version=3.10

# Exclusions
sonar.exclusions=**/node_modules/**,**/build/**,**/__pycache__/**,**/dist/**

# Language settings
sonar.sourceEncoding=UTF-8
