apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ticketing-backend
  template:
    metadata:
      labels:
        app: ticketing-backend
    spec:
      containers:
        - name: backend
          image: dhiasaidan/my-ticketing-backend:latest
          imagePullPolicy: Always   # <--- C'EST ICI !
          env:
            - name: DB_HOST
              value: "db-service"
            - name: DB_NAME
              value: "ticket_db"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db-password
            - name: LDAP_SERVER_URL
              value: "ldap://openldap-service:389"
            - name: LDAP_BASE_DN
              value: "dc=sotupa,dc=local"
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: admin-username
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: admin-password
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: ticketing-backend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001