apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  db-password: "postgres"
  admin-username: "admin"
  admin-password: "admin"
  ldap-admin-password: "admin123"
  grafana-admin-password: "admin"
